const PostsActionTypes = {
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    UPLOAD_POST_START: 'UPLOAD_POST_START',
    UPLOAD_POST_SUCCESS: 'UPLOAD_POST_SUCCESS',
    UPLOAD_POST_FAILURE: 'UPLOAD_POST_FAILURE',
    LIKE_POST: 'LIKE_POST',
    COMMENT_POST: 'COMMENT_POST',
    UPDATE_POST: 'UPDATE_POST'
};

export default PostsActionTypes;